# Generated by Django 5.1.1 on 2024-10-27 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Garden', '0002_remove_garden_guia'),
        ('Plants', '0004_alter_category_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garden',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='garden',
            name='planta',
        ),
        migrations.RemoveField(
            model_name='garden',
            name='usuario',
        ),
        migrations.AddField(
            model_name='garden',
            name='plants',
            field=models.ManyToManyField(blank=True, related_name='gardens', to='Plants.plants'),
        ),
        migrations.AddField(
            model_name='garden',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='garden', to=settings.AUTH_USER_MODEL),
        ),
    ]
