# Generated by Django 5.1.1 on 2024-10-12 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plants', '0003_category_alter_plants_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
