# Generated by Django 5.1.1 on 2024-11-05 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plants', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plants',
            name='nombre_cientifico',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
