# Generated by Django 5.1.1 on 2024-11-06 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guides', '0002_alter_guides_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guides',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
