# Generated by Django 5.1.1 on 2024-11-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guides', '0003_alter_guides_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='guides',
            name='subtitulo',
            field=models.CharField(default='Pasos para cuidar '),
        ),
        migrations.AddField(
            model_name='guides',
            name='titulo',
            field=models.CharField(default='Guia de cuidado de'),
        ),
    ]
