# Generated by Django 5.1.1 on 2024-10-31 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_customuser_nombre_alter_customuser_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='imagen',
            field=models.ImageField(null=True, upload_to='user/'),
        ),
    ]
