# Generated by Django 5.1.1 on 2024-11-01 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_customuser_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='user/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
